### ISSUE TITLE
Include On-Start Notifications

### ISSUE THREAD

**Issue by jackspirou** [jmccann/drone-hipchat#2]
Currently the HipChat plugin only sends a notification on build success or failure.  A notification to indicate a build has started should also be included.

**Comment by jackspirou** [comment]
@bradrydzewski I hate to admit it, but I think i'm a bit stuck and need some help to get started.  Can you give some hints as to how a HipChat notification upon on-start might work with version `.4`?  

Does it have something to do with https://godoc.org/github.com/drone/drone-go/drone#Activity ? 

Or does have to do with notify `on_started` `on_success` `on_failure` like version `.3` did?  So that any notification plugin would get executed on `on_started: true` ?

``` go
notify:
  hipchat:
    room: HipChatRoom
    token: HipChatToken
    on_started: true
    on_success: true
    on_failure: true
```

Thanks for the help!

**Comment by bradrydzewski** [comment]
@jackspirou this one is a bit more tricky

In 0.3 the individual notification plugin was in charge of deciding if / when it should be executed. In 0.4 we moved this logic outside of the individual plugin code to the build runner. Since this logic was being duplicated by every plugin, it made sense to pull this out into the build runner. So now the build runner decides if and when a plugin should execute based on the `when` clause. So the good news is there is nothing you need to do inside the hipchat plugin.

In 0.4 we also had to account for matrix builds. Unlike publish and deploy plugins that are executed after the build step, we cannot execute notifications until all other builds in the matrix are complete. So first we run each build in the matrix, then we trigger all notifications when all matrix jobs complete.

We don't currently trigger notification plugins prior to the build matrix starting, which means we can't yet send `on_started` notifications. This change would need to happen in the Drone server (which schedules these high level operations). We'd also need to modify the build runner code to account for `on_started` notifications and its filter logic.

Triggering `on_started` notifications is definitely possible and something I've been planning on implementing, however, it will touch a few different layers and require a bit of refactoring which I think complicates things a bit.

We could probably split this change into pieces, and implement them incrementally over the coming weeks if you think that might make sense.

**Comment by jackspirou** [comment]
@bradrydzewski thanks for the explanation above!!! Extremely helpful. 

So i'm guessing the build runner you referred to above is the `runner` package in https://github.com/drone/drone-exec.  Based on what you said above, and scanning through the package quick, it looks to me that all the changes we need to accomplish triggering `on_started` notification plugins would be local to this package.  Is that correct?  

Is what your envisioning something like: 
1. runner starts and does init stuff
2. runner triggers `on_started` notification plugins
3. runner executes matrix build
4. matrix build completes
5. runner triggers `on_completed` notification plugins`and/or publish plugins`

Thanks for the help on getting me started.  Are there any docs on the architecture of how `.4` is built?  If not no biggie, just thought I would ask so I don't have to unnecessarily bug you.

And yes, if you have some ideas on how to get this started I would be happy to add smaller incremental changes over the next few weeks.  Let me know how you want to do this! :-P

**Comment by bradrydzewski** [comment]
this is handled at the drone level (not the plugin level) and is possible in 0.5 :smile:
